### ISSUE TITLE
Widgets layout dissapear after panel restart

### ISSUE THREAD

**Issue by ilexpl01** [blakadder/nspanel#19]
Hello,

I have flashed Tasmota to my NSPanel (EU). I can add/remove widgets using MQTT publish command.

After the restart all my changes diseppear - widgets schema looks as factory setup.

Any hint ?

**Comment by joBr99** [comment]
Hey, 
this should be normal behaviour, you can configure your widgets in the nspanel.be driver script itself or send them every times your nspanel starts.

**Comment by ilexpl01** [comment]
OK, I thought so :) Where can I look for any examples or wiki how to adjust nspanel.be script ?

**Comment by ilexpl01** [comment]
Wow, that was easy, how could I miss that - thank You a lot !

Two more questions if I may:

1. Screen goes off after couple of minutes - is there an option to keep it on permanently ? I have tried with NSPDim - not much luck
2. Is there any command to dimm the screen to specified level over mqtt ?

**Comment by joBr99** [comment]
According to Blakadder's Protocol docs you have to send the following message to keep the screen always on:
{"HMI_dimOpen":0}

https://blakadder.github.io/nspanel/

**Comment by ilexpl01** [comment]
It does work -thx !
