### ISSUE TITLE
Add dimmer only (feature)

### ISSUE THREAD

**Issue by Matten-Matten** [blakadder/nspanel#23]
Hi ,
first of all great work!

I would like to choose a widget that can only dim without the white value.

is that somehow possible?

greeting
Matten Matten

**Comment by joBr99** [comment]
Same for this issue, you can only use the widgets that are already in the stock firmware, if you want to have a custom UI, you have to go with your own or use one of the display firmware projects linked in Readme.

If you want to use Tasmota you can try:

- NxPanel (currently with openhab backend, but not limited to openhab) 

or 

- my lovelance project (currently with homeassistant/nodered backend) 

For the rest of the linked projects you want to have esphome.

**Comment by Matten-Matten** [comment]
ok, thanks.
