### ISSUE TITLE
widget feature via mqtt

### ISSUE THREAD

**Issue by Matten-Matten** [blakadder/nspanel#24]
Hi there,

if a scene is created as a widget, only the ID is displayed in the payload (mqtt).

`{"NSPanel":{"id":"6"}}`

Is it possible to integrate a status string with the value "scene"?

greetings 
Matten Matten

**Comment by joBr99** [comment]
No, the json messages are coming from the stock nspanel firmware, this berry driver only forward's them over mqtt. This must be changed in the stock firmware and most likely sonoff won't do this :)

**Comment by Matten-Matten** [comment]
okay thanks. I close it.
