### ISSUE TITLE
Wrong external temperature reading

### ISSUE THREAD

**Issue by iandronowicz** [blakadder/nspanel#31]
Hi, first of all: thanks for your work, this is great I really appreciate it.

I’ve just flashed my first NSPanel and got everything running ok, except for the external temperature reading, I don’t know it may be a faulty sensor? The nspanel is brand new, but it shows 4C when it’s actually around 23C. Couldn’t get around it, the ESP32 cpu sensor I think it’s fine around 53C.

Any suggestions? Thanks!
![6930043D-8149-4AD0-A8D3-8356367709BE](https://user-images.githubusercontent.com/250746/157804525-2415b734-dff5-4bc8-afde-8392f826e25b.jpeg)

**Comment by blakadder** [comment]
Calibrate using command [AdcParam](https://tasmota.github.io/docs/Commands/#adcparam)

**Comment by iandronowicz** [comment]
Thanks!

Just in case, this worked for me: Adcparam1 2,13500,10000,3950

tested with 2 different temp sensor placed next to the nspanel

**Comment by s-hemer** [comment]
Thanks for sharing your parameters. Yet, for me this resulted in around 16°C whereas my multimeter measures around 18°C. 
Other parameters suggested elsewhere:
ADCParam 2,64000,10000,3950 -> results in around -12 °C
ADCParam 2,11200,10000,3950 -> results in around 20 °C
ADCParam 2,14600,10000,3950 -> as expected lower than with your parameters, around 15 °C

So to sum up: the second parameter is the one that seems to be played around with.
