### ISSUE TITLE
Stock tft file for EU

### ISSUE THREAD

**Issue by gonzzzales** [blakadder/nspanel#36]
Hi!
I tried to do some expiriments with NSPanel, and now i have replaced firmwre for Nextion display. I cant find the original stock tft file for EU version of NSpanel in internet. Maybe someone has something similar?

**Comment by eokgnah** [comment]
https://cdn.discordapp.com/attachments/538814618106331139/925351768852951050/ns-panel.tft
here it is...
found it myself in this post:
https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869

**Comment by stingone** [comment]
> https://cdn.discordapp.com/attachments/538814618106331139/925351768852951050/ns-panel.tft here it is... found it myself in this post: https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869

Is this the red or blue version? And how can this be uploaded if tssmota has been flashed?

**Comment by joBr99** [comment]
red or blue version?

It cannot be flashed with this berry driver, you have to use this one for example:
https://github.com/joBr99/nspanel-lovelace-ui/tree/main/tasmota

**Comment by stingone** [comment]
> red or blue version?
> 
> It cannot be flashed with this berry driver, you have to use this one for example: https://github.com/joBr99/nspanel-lovelace-ui/tree/main/tasmota

The stock tft file of the nspanel has 2 different backgrounds.  The original stock has a Black/red background and the latest has a blue/White one.

**Comment by joBr99** [comment]
The only version of the stock firmware that is around on the internet is an early version that has been extracted from the flash chip of the nextion screen. Probably the first firmware version that was out there from nextion.
