### ISSUE TITLE
Relais schalten nicht zuverlässig auf Tastendruck

### ISSUE THREAD

**Issue by Matten-Matten** [blakadder/nspanel#38]
Hallo, 
wenn das modul keine WLAN Verbindung hat oder das wetter aus irgendeinem Grund nicht abrufen kann, funktioniert das Relais nicht zuverlässig auf den Tasten Druck. Ist das möglich  abzuändern? Vielleicht in ein extra Script auslagern und gesondert abzurufen?

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
? Gibt es hierfür bereits eine Abhilfe?

**Comment by CybDis** [comment]
der Entwickler ist nicht deutschsprachig - you should write in English if you want support

**Comment by Matten-Matten** [comment]
Danke für den Tipp

**Comment by CybDis** [comment]
> Hallo, wenn das modul keine WLAN Verbindung hat oder das wetter aus irgendeinem Grund nicht abrufen kann, funktioniert das Relais nicht zuverlässig auf den Tasten Druck. Ist das möglich abzuändern? Vielleicht in ein extra Script auslagern und gesondert abzurufen?
> 


I made the experience that this is a tasmota thing - if wifi is bad and you haven't setup an alternative wifi, it keeps rebooting.

Workaround that worked for me: Configure a second wifi. It doesn't need to exist or work, just a second wifi must be configured - so it switches/retries instead of rebooting, what makes the buttons stay working

**Comment by joBr99** [comment]
Yeah, I don't think that blakadder speaks german. Also this isn't related to the berry driver, the buttons and the relays on the nspanel are directly connected to the esp32, the berry driver is not involved into that.

I guess to avoid this wifi rebooting issue, you should config the WifiConfig Setting.
https://tasmota.github.io/docs/Commands/#wi-fi

-----------------

Ja, ich würde auch sagen Blakadder spricht kein Deutsch. Weiterhin hat das hier nix mit dem Berry-Treiber zu tun, die Tasten und Relais am nspanel sind direkt mit dem esp32 verbunden, der Berry-Treiber hat mit denen nichts zu tun.

Um das Neustart Problem zu beheben ist das hier vermutlich der richtige Weg, `WifiConfig 5` sollte dafür sorgen, dass Tasmota nicht mehr neustartet.

https://tasmota.github.io/docs/Commands/#wi-fi

![Bild](https://user-images.githubusercontent.com/29555657/170244445-58eda327-24e1-43bc-a0fa-4206291cd3d9.png)

**Comment by Matten-Matten** [comment]
Widiconfig 5 is set.... I test it with a second Network.

Thanks on all!
