### ISSUE TITLE
Direct upload to nextion without esphome ? 

### ISSUE THREAD

**Issue by sigmounte** [blakadder/nspanel#40]
Hi ! 

Thanks for your tutorial about the NsPanel 

Were you able to do a direct upload of the tft file to the nexion display without using esphome ? 

Thanks !

**Comment by joBr99** [comment]
Which tft do you mean? This berry driver is focused on the stock firmware/tft and only works with the custom serial protocol of the stock firmware. So uploading TFT files in this berry driver would only be useful for updates of the stock firmware.
