### ISSUE TITLE
[SOLDVED]{"NSPanel":{"error":2}} ... what is it ?

### ISSUE THREAD

**Issue by pploume** [blakadder/nspanel#41]
Hi,

NSPanel flashed with tasmota32-nspanel.bin

HA mqtt configured and working, 
message well received and command send : 
**15:46:53.418 MQT: homeassistant/nspanel1/RESULT = {"NSPSend":"Done"}** 
the command is :
topic -> homeassistant/nspanel1/cmnd/NSPsend
payload : 10
(I've also tryied with payload template ... same error  #2)

If I send mqtt through "mqtt explorer", if works ... no error

I guess my HA mqtt message is malformed ... can't see it
:(

SOLVED : the mqtt template payload has to be in quote : '{"temperature":87}'
any suggestion, any ideas ?
(btw : where are defined the errors ?)

**Comment by joBr99** [comment]
since this is reverse engineered and there is no offical documentation from sonoff, error 2 could be anything

only ocurence documented by blakadder is on using non an existing numbers for hmi weather

https://blakadder.github.io/nspanel/
