### ISSUE TITLE
Question : Edit UI with Nextion

### ISSUE THREAD

**Issue by CyrielRct** [blakadder/nspanel#44]
Do we have any way to change the UI with Nextion Editor ? 

I'm looking at a way of showing the temperature of my pool. 

Until now I tried : 

- Use the indoor temperature to show the swimming pool one . this one is replaced automatically every min unfortunately
- Use the Thermostat screen control but this one I never found the command to replace the temperature in the middle - looks to be linked with the indoor temp

**Comment by joBr99** [comment]
> Do we have any way to change the UI with Nextion Editor ?

No, you have to use a custom UI for this, see Resources in Readme

> Use the indoor temperature to show the swimming pool one . this one is replaced automatically every min unfortunately

This is done by this line in the driver, you can remove/change that code.

https://github.com/blakadder/nspanel/blob/01db07ac52109204bb1df09535e96e40669d43c1/nspanel.be#L411
