### ISSUE TITLE
Change dateformat shown on screen ?

### ISSUE THREAD

**Issue by TokTias** [blakadder/nspanel#48]
Hi !
Is there any possibility to change the date format (currently set to the US-standard MM/DD + weekday), preferably definable via a Console command ? (Personally, I am looking to get it to YYYY-MM-DD + the weekday abbreviation.)

Cheers !
/T

**Comment by joBr99** [comment]
No, the firmware is getting the date via a json command, so there is no way to change it with the stock display firmware.

https://github.com/blakadder/nspanel/blob/main/nspanel.be#L155

-----------------------------------

Shameless plug for my HMI Project, you can display whatever date format you want with it, if you are an HomeAssistant, ioBroker (or ip-symcon) user there are Integrations available. 

If you are using some different automation system and you have some scripting/programming skills and you want to integrate it with your system, feel free to ask and I will guide you how to get stared with the message protocol the panel is expecting with my project.

**Comment by TokTias** [comment]
Hi !
Thanks for your fast reply. I use domoticz and I do have C/C++ and scripting experience for a few decades. I have also been coding for the Nextion screens so I was perhaps just hoping for a simple way to write directly to the Text label showing the date from the ESP-code, perhaps just set up a timer that sends the year/month/day and weekday from the RTC to the Nextion Txt label.
(I'll see if I can find the person you mentioned that made something for domoticz.)

**Comment by joBr99** [comment]
See these two for the domoticz stuff:

https://github.com/joBr99/nspanel-lovelace-ui/issues?q=domoticz

I summerizesed the first part of getting something to work with my HMI here: https://github.com/joBr99/nspanel-lovelace-ui/issues/436#issuecomment-1236208688

Hit me up on Unofficial Nextion Discord, I guess that would be easier. https://discord.gg/98V7qp4
