### ISSUE TITLE
Tasmota compilation

### ISSUE THREAD

**Issue by djlukas7** [blakadder/nspanel#52]
Does the tasmota build support temperature sensors like sht3x?
If not, could you please provide a compilation with support for these sensors? I would like to replace the original temperature sensor with the sht30 sensor.

**Comment by blakadder** [comment]
https://tasmota.github.io/docs/Compile-your-build/

**Comment by joBr99** [comment]
didn't check, but if it wasn't removed in the nspanel build it should be included by default

https://tasmota.github.io/docs/SHT30/
>This feature is included only in tasmota-sensors and tasmota32 binaries
