### ISSUE TITLE
Freeze at Settings Scrren

### ISSUE THREAD

**Issue by SyncroMischi** [blakadder/nspanel#53]
Hy all there,
The NSPanel with Tasmota works fine I managed to set Widgets over Mqtt and deal with received Messages. The strange behavior I have is that when I swiped to Settings Screen on the NSPanel it self (swiping from up to down). It is not possible to leave this Screen. I can set All settings which are displayed in the Screen but coming back to Homescreen it's not possible. My solution was to restart Panel over tasmota but I think that's not how the Designer has planed it ;)

**Comment by joBr99** [comment]
>When initially drawing widgets you need to send commands for all 8 indexes, if you want to keep an index empty send a delete command for that index.

You need to send widgets for all 8 positions otherwise it will freeze.

**Comment by SyncroMischi** [comment]
Okey I try it. But how I get back from the settings screen to home screen?

**Comment by SyncroMischi** [comment]
Perfect Thank you are Great !!!!!!!!!!!
When I send the whole Widget Config at once there is no freeze in Settings Screen
