### ISSUE TITLE
Locked by:   Wipe down to "Settings of the screen brightness and sleep time"

### ISSUE THREAD

**Issue by super-Alfi** [blakadder/nspanel#55]
Env: Sonoff NSPanel Tasmota 12.2.0 (tasmota32-nspanel.bin)  

A dropdown changes any current panel to 
a setup panel to control  screen brightness, sleep time and 24-Hour changes.

But now - there is no way back to the previous panel ...

**Comment by super-Alfi** [comment]
Have identified the problem.
When restarting, I remove the 8 standard icons on "Page 2".
These are then replaced by only 4 new switches.
If this constellation is swiped from top to bottom,
the "Brightness-Sleep-24Hour" panel appears and can no longer be "swiped up".

**Comment by joBr99** [comment]
>When initially drawing widgets you need to send commands for all 8 indexes, if you want to keep an index empty send a delete command for that index.

https://blakadder.github.io/nspanel/

**Comment by super-Alfi** [comment]
as soon as you get it right, it goes

**Comment by super-Alfi** [comment]
thanks !!!
