### ISSUE TITLE
How to enable NSPANEL PSRAM ?

### ISSUE THREAD

**Issue by cyberumut** [blakadder/nspanel#57]
How to enable NSPANEL PSRAM ?
I have 16mb psram on the nspanel circuit but how can I activate it?

**Comment by joBr99** [comment]
Just use the correct tasmota version for the nspanel (tasmota32-nspanel.bin)

**Comment by cyberumut** [comment]
> Just use the correct tasmota version for the nspanel (tasmota32-nspanel.bin)

Do I need to do a physical intervention on the pcb?
I need to use it for a different project. can i activate without using tasmota

**Comment by joBr99** [comment]
lol this Project is for tasmota, if you need PSRAM on a different project ask there it's a software thing, no need to change anything on the Hardware
