### ISSUE TITLE
NSpanel psram not working

### ISSUE THREAD

**Issue by cyberumut** [blakadder/nspanel#58]
I have nspanel but psram is not working.
psram available on circuit 16mb 
how can i run it via tasmota?
![image](https://user-images.githubusercontent.com/105754498/218284006-7589d696-8312-4aae-b505-0fd32c129225.png)

**Comment by joBr99** [comment]
Are you running the correct build of tasmota?

**Comment by cyberumut** [comment]
> Are you running the correct build of tasmota?


yes latest version for nspanel

**Comment by cyberumut** [comment]
> Are you running the correct build of tasmota?

`void setup() {
  
  Serial.begin(115200);
  //delay(2000);
// pinMode(3,OUTPUT);
// delay(200);
//
//  digitalWrite(3,HIGH);
//  delay(500);

  
  
 // Serial.setDebugOutput(true);
  
}

void loop() {
  Serial.print("Total heap:");
  Serial.println(ESP.getHeapSize());
  Serial.print("Free heap: ");
  Serial.println(ESP.getFreeHeap());
//  Serial.print("TOtal psram size : ");
//  Serial.println(esp_spiram_get_size());
  Serial.print("PSRAM INIT : ");
  Serial.println(psramInit());
   Serial.print("PSRAM Found : ");
  Serial.println(psramFound());
if(psramFound()){
    
  Serial.print("Total PSRAM using caps:");
  Serial.println(heap_caps_get_free_size(MALLOC_CAP_SPIRAM));
  Serial.print("Total PSRAM:");
  Serial.println(ESP.getPsramSize());
  Serial.print("Free PSRAM: ");
  Serial.println(ESP.getFreePsram());
  
  }
  delay(2000);
  }`

I uploaded this code structure to test if it sees psram and it doesn't find psram, it prints it as 0

**Comment by cyberumut** [comment]
psram is connected on different pins than normal dude ?

**Comment by joBr99** [comment]
what has this arduino code to do with tasmota?

**Comment by cyberumut** [comment]
> what has this arduino code to do with tasmota?

psram'in çalışıp çalışmadığını kontrol etmek için denedim

**Comment by joBr99** [comment]
I don't see any signs of psram in recent tasmota version on my panel.

Try this build https://github.com/blakadder/nspanel/blob/main/tasmota32-nspanel.bin

If it's showing there it might be indeed broken in the latest version of tasmota.

**Comment by edwardtfn** [comment]
@cyberumut, have you ever succeeded on using PSRAM in your NSPanel?
